# Generated by Django 6.0.5 on 2026-05-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, verbose_name='社團名稱')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='人數上限')),
                ('current_members', models.PositiveIntegerField(default=0, verbose_name='目前人數')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_start_date', models.DateTimeField(blank=True, null=True, verbose_name='轉社開始時間')),
                ('transfer_end_date', models.DateTimeField(blank=True, null=True, verbose_name='轉社結束時間')),
            ],
            options={
                'verbose_name': '系統設定',
                'verbose_name_plural': '系統設定',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='學號')),
                ('password', models.CharField(max_length=128, verbose_name='密碼')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('class_number', models.CharField(max_length=20, verbose_name='班級座號')),
                ('role', models.CharField(choices=[('student', '學生'), ('president', '社長'), ('teacher', '老師'), ('discipline', '訓育組')], default='student', max_length=20, verbose_name='角色')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='電子郵件')),
            ],
        ),
        migrations.CreateModel(
            name='TransferApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_original_president', '待原社長審核'), ('pending_original_teacher', '待原老師審核'), ('pending_new_president', '待新社長審核'), ('pending_new_teacher', '待新老師審核'), ('pending_discipline', '待訓育組審核'), ('new_club_rejected', '新社團拒絕/額滿需重選'), ('approved', '申請成功'), ('rejected', '申請失敗')], default='pending_original_president', max_length=40, verbose_name='申請狀態')),
                ('is_original_club_approved', models.BooleanField(default=False, verbose_name='原社團已同意')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('new_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_applications', to='default.club', verbose_name='目標社團')),
                ('original_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_applications', to='default.club', verbose_name='原社團')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_applications', to='default.user', verbose_name='申請學生')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presided_clubs', to='default.user', verbose_name='社長'),
        ),
        migrations.AddField(
            model_name='club',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_clubs', to='default.user', verbose_name='指導老師'),
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', '同意'), ('rejected', '拒絕')], max_length=20, verbose_name='動作')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='default.transferapplication', verbose_name='申請單')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='default.user', verbose_name='審核者')),
            ],
        ),
    ]
