# Generated by Django 6.0.5 on 2026-05-24 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='社團介紹'),
        ),
        migrations.AddField(
            model_name='club',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to='club_descriptions/', verbose_name='社團介紹文件'),
        ),
        migrations.AddField(
            model_name='club',
            name='description_url',
            field=models.URLField(blank=True, null=True, verbose_name='社團介紹網址'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approval_logs', to='default.transferapplication', verbose_name='申請單'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approval_logs', to='default.user', verbose_name='審核者'),
        ),
        migrations.AlterField(
            model_name='club',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='presided_clubs', to='default.user', verbose_name='社長'),
        ),
        migrations.AlterField(
            model_name='club',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coached_clubs', to='default.user', verbose_name='指導老師'),
        ),
        migrations.AlterField(
            model_name='transferapplication',
            name='new_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_applications', to='default.club', verbose_name='目標社團'),
        ),
        migrations.AlterField(
            model_name='transferapplication',
            name='original_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='original_applications', to='default.club', verbose_name='原社團'),
        ),
        migrations.AlterField(
            model_name='transferapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_applications', to='default.user', verbose_name='申請學生'),
        ),
    ]
