# Generated by Django 6.0.5 on 2026-05-24 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_club_description_club_description_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='description_file',
        ),
        migrations.RemoveField(
            model_name='user',
            name='class_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='登入名稱'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='學號')),
                ('class_number', models.CharField(max_length=20, verbose_name='班級座號')),
                ('role', models.CharField(choices=[('student', '學生'), ('president', '社長'), ('teacher', '老師'), ('discipline', '訓育組')], default='student', max_length=20, verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='default.user')),
            ],
        ),
        migrations.CreateModel(
            name='Superviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50, unique=True, verbose_name='教師編號')),
                ('role', models.CharField(choices=[('president', '社長'), ('discipline', '訓育組')], default='discipline', max_length=20, verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='default.user')),
            ],
        ),
    ]
