# Generated by Django 6.0.5 on 2026-05-24 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_remove_club_description_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDescriptionModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='社團介紹')),
                ('description_url', models.URLField(blank=True, null=True, verbose_name='社團介紹網址')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已批准'), ('rejected', '已拒絕')], default='pending', max_length=20, verbose_name='狀態')),
                ('approval_comment', models.TextField(blank=True, null=True, verbose_name='批注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_modifications', to='default.user', verbose_name='批准者')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_modifications', to='default.club', verbose_name='社團')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_modifications', to='default.user', verbose_name='提交者')),
            ],
            options={
                'verbose_name': '社團描述修改',
                'verbose_name_plural': '社團描述修改',
            },
        ),
        migrations.CreateModel(
            name='ClubDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文件標題')),
                ('file', models.FileField(upload_to='club_documents/', verbose_name='文件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='default.club', verbose_name='社團')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_documents', to='default.user', verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '社團文件',
                'verbose_name_plural': '社團文件',
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='default.club', verbose_name='社團')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='default.user', verbose_name='學生')),
            ],
            options={
                'verbose_name': '社團成員',
                'verbose_name_plural': '社團成員',
                'unique_together': {('club', 'student')},
            },
        ),
    ]
