# Generated by Django 6.0.5 on 2026-05-24 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_clubdescriptionmodification_clubdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubModificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='club_description_modifications/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_documents', to='default.clubdescriptionmodification')),
            ],
            options={
                'verbose_name': 'pending club description document',
                'verbose_name_plural': 'pending club description documents',
            },
        ),
    ]
