# Generated by Django 6.0.5 on 2026-05-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_clubmodificationdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmodificationdocument',
            options={'verbose_name': '待審核社團介紹文件', 'verbose_name_plural': '待審核社團介紹文件'},
        ),
        migrations.AlterField(
            model_name='clubdescriptionmodification',
            name='approval_comment',
            field=models.TextField(blank=True, null=True, verbose_name='審核備註'),
        ),
        migrations.AlterField(
            model_name='clubdescriptionmodification',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_modifications', to='default.user', verbose_name='審核者'),
        ),
        migrations.AlterField(
            model_name='clubdescriptionmodification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='送出時間'),
        ),
        migrations.AlterField(
            model_name='clubdescriptionmodification',
            name='status',
            field=models.CharField(choices=[('pending', '待審核'), ('approved', '已核准'), ('rejected', '已退回')], default='pending', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='clubdescriptionmodification',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_modifications', to='default.user', verbose_name='送出者'),
        ),
    ]
